import '@/styles/globals.css';
import Script from "next/script";
import React from "react";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="de">
    <head>
        <Script src="https://player.vimeo.com/api/player.js" />
    </head>
      <body>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
